defaults:
  - experiment/lightning_data_module: cifar10
  - experiment/lightning_module: image_classification
  - experiment/lightning_trainer: trainer
  - model: resnet18
  - optim: sgd

experiment:
  lightning_module:
    model: ${model}
    optim: ${optim}
