# Note: Hydra currently doesn't support partial functions
# and optimizers need the model to be instantiated and provided
# as input to the optimizer, e.g.,
#
# >> model = resnet18()
# >> optim = torch.optim.SGD(model.parameters(), lr=0.1)
#
# This config provides an "optimizer" field as a string that is checked in
# `image_classifier.model.ImageClassifer.configure_optimizers`
optimizer: "adam"
params:
  lr: 0.1
